export const DATA_PRODUCTS = [
  {
    product_id: "dp-reg-positions",
    product_name: "Regulatory Positions",
    business_domain: "Regulatory Reporting",
    owner: "Priya Sharma",
    description:
      "Daily regulatory position snapshot covering capital adequacy and counterparty exposure — reference product.",
    source_systems: ["Oracle Financials", "Risk Platform", "SYNAPSE-REG-PROD"],
    bronze_entities: ["stg_raw_positions", "stg_counterparty_ref"],
    silver_entities: ["fact_positions_cleansed", "dim_counterparty_validated"],
    gold_marts: ["agg_capital_requirements", "mart_exposure_summary"],
    freshness_target: "T+1 by 08:00 UTC",
    has_contract: true,
    readiness_score: 61.0,
    readiness_band: "needs_review",
    consumer_reports: ["pbi-001", "pbi-002"],
  },
  {
    product_id: "dp-claims-payments",
    product_name: "Claims Payment Analytics",
    business_domain: "Claims Finance",
    owner: "Marcus Chen",
    description:
      "Insurance claims payment flows, reserve calculations, and fraud signal indicators — reference product.",
    source_systems: ["Policy Management System", "ML Platform", "SYNAPSE-CLAIMS-PROD"],
    bronze_entities: ["stg_claims_raw", "stg_policy_ref"],
    silver_entities: ["fact_payments_validated", "dim_policy_cleansed"],
    gold_marts: ["mart_claims_summary", "agg_reserve_summary"],
    freshness_target: "T+0 every 4 hours",
    has_contract: true,
    readiness_score: 44.0,
    readiness_band: "blocked",
    consumer_reports: ["pbi-003", "pbi-004"],
  },
  {
    product_id: "dp-retail-sales",
    product_name: "Retail Sales Performance",
    business_domain: "Retail Sales",
    owner: "Fatima Al-Rashid",
    description:
      "Point-of-sale transaction volumes, regional performance, and product category analysis — reference product.",
    source_systems: ["POS System", "ERP", "SYNAPSE-RETAIL-UAT"],
    bronze_entities: ["stg_sales_raw", "stg_product_ref"],
    silver_entities: ["fact_sales_validated", "dim_product_cleansed"],
    gold_marts: ["mart_sales_by_region", "mart_product_performance"],
    freshness_target: "T+1 by 06:00 UTC",
    has_contract: true,
    readiness_score: 82.0,
    readiness_band: "ready",
    consumer_reports: ["pbi-005", "pbi-006"],
  },
  {
    product_id: "dp-customer-segments",
    product_name: "Customer Segment Analytics",
    business_domain: "Customer Analytics",
    owner: "James Okonkwo",
    description:
      "Customer lifetime value, behavioural cohorts, and segment-level engagement metrics — reference product.",
    source_systems: ["CRM", "SYNAPSE-CUSTOMER-DEV"],
    bronze_entities: ["stg_customer_events_raw"],
    silver_entities: ["fact_customer_events_validated", "dim_customer_cleansed"],
    gold_marts: ["mart_customer_ltv", "mart_segment_summary"],
    freshness_target: "T+1 weekly refresh",
    has_contract: false,
    readiness_score: 58.0,
    readiness_band: "needs_review",
    consumer_reports: ["pbi-007"],
  },
  {
    product_id: "dp-ops-health",
    product_name: "Operations Health",
    business_domain: "Operations Monitoring",
    owner: "Lin Wei",
    description:
      "Pipeline SLA tracking, cost attribution by domain, and infrastructure health signals — reference product.",
    source_systems: ["Azure Monitor", "Azure Cost Management", "SYNAPSE-OPS-SHARED"],
    bronze_entities: ["stg_pipeline_runs_raw"],
    silver_entities: ["fact_pipeline_runs_validated"],
    gold_marts: ["mart_ops_sla", "mart_cost_by_domain"],
    freshness_target: "Hourly",
    has_contract: false,
    readiness_score: 74.0,
    readiness_band: "ready",
    consumer_reports: ["pbi-008"],
  },
];

export const DATA_CONTRACTS: Record<string, object> = {
  "dp-reg-positions": {
    product_id: "dp-reg-positions",
    product_name: "Regulatory Positions",
    owner: "Priya Sharma",
    business_domain: "Regulatory Reporting",
    source_systems: ["Oracle Financials", "Risk Platform"],
    primary_key: "position_id",
    freshness_expectation: "Available by 08:00 UTC on T+1 business day",
    columns: [
      { name: "position_id", data_type: "STRING", nullable: false, description: "Unique position identifier" },
      { name: "reporting_date", data_type: "DATE", nullable: false, description: "Regulatory reporting date" },
      { name: "counterparty_id", data_type: "STRING", nullable: false, description: "Counterparty reference" },
      {
        name: "instrument_type",
        data_type: "STRING",
        nullable: false,
        description: "Financial instrument classification",
        allowed_categories: ["BOND", "EQUITY", "DERIVATIVE", "FX", "REPO"],
      },
      {
        name: "notional_amount",
        data_type: "DECIMAL(18,4)",
        nullable: false,
        description: "Notional value in base currency",
        allowed_range: "0 to 1000000000",
      },
      {
        name: "risk_weight",
        data_type: "DECIMAL(5,4)",
        nullable: false,
        description: "Basel III risk weight factor",
        allowed_range: "0 to 1.5",
      },
      {
        name: "capital_charge",
        data_type: "DECIMAL(18,4)",
        nullable: false,
        description: "Computed capital charge amount",
      },
      {
        name: "data_classification",
        data_type: "STRING",
        nullable: false,
        description: "PII/sensitivity classification",
        allowed_categories: ["CONFIDENTIAL", "RESTRICTED", "PUBLIC"],
      },
    ],
    reconciliation_rules: [
      {
        rule_id: "rule-reg-001",
        rule_type: "row_count",
        description: "Row count must match source within 0.01%",
        severity: "critical",
        column: null,
        threshold: 0.0001,
      },
      {
        rule_id: "rule-reg-002",
        rule_type: "null_rate",
        description: "counterparty_id null rate must be 0",
        severity: "critical",
        column: "counterparty_id",
        threshold: 0,
      },
      {
        rule_id: "rule-reg-003",
        rule_type: "balance_check",
        description: "Sum of capital_charge must match source within 0.1%",
        severity: "critical",
        column: "capital_charge",
        threshold: 0.001,
      },
      {
        rule_id: "rule-reg-004",
        rule_type: "duplicate_key",
        description: "position_id must be unique per reporting_date",
        severity: "critical",
        column: "position_id",
        threshold: 0,
      },
      {
        rule_id: "rule-reg-005",
        rule_type: "category_distribution",
        description: "instrument_type distribution must not shift >5%",
        severity: "high",
        column: "instrument_type",
        threshold: 0.05,
      },
    ],
    downstream_consumers: ["Regulatory Capital Dashboard", "Counterparty Exposure Monitor", "Reg Reporting Engine"],
  },
  "dp-claims-payments": {
    product_id: "dp-claims-payments",
    product_name: "Claims Payment Analytics",
    owner: "Marcus Chen",
    business_domain: "Claims Finance",
    source_systems: ["Policy Management System", "ML Platform"],
    primary_key: "payment_id",
    freshness_expectation: "Updated every 4 hours via streaming ingestion",
    columns: [
      { name: "payment_id", data_type: "STRING", nullable: false, description: "Unique payment identifier" },
      { name: "claim_id", data_type: "STRING", nullable: false, description: "Parent claim reference" },
      { name: "policy_id", data_type: "STRING", nullable: false, description: "Policy reference" },
      { name: "payment_date", data_type: "DATE", nullable: false, description: "Payment processing date" },
      {
        name: "payment_amount",
        data_type: "DECIMAL(14,2)",
        nullable: false,
        description: "Payment amount in GBP",
        allowed_range: "0 to 10000000",
      },
      {
        name: "payment_type",
        data_type: "STRING",
        nullable: false,
        description: "Nature of payment",
        allowed_categories: ["CLAIM_SETTLEMENT", "PARTIAL_PAYMENT", "RESERVE_RELEASE", "SALVAGE"],
      },
      {
        name: "fraud_score",
        data_type: "DECIMAL(4,3)",
        nullable: true,
        description: "ML fraud signal [0-1]",
        allowed_range: "0 to 1",
      },
      {
        name: "status",
        data_type: "STRING",
        nullable: false,
        description: "Payment lifecycle status",
        allowed_categories: ["PENDING", "PROCESSED", "REJECTED", "REVERSED"],
      },
    ],
    reconciliation_rules: [
      {
        rule_id: "rule-claims-001",
        rule_type: "row_count",
        description: "Payment count must match source within 0.1%",
        severity: "high",
        column: null,
        threshold: 0.001,
      },
      {
        rule_id: "rule-claims-002",
        rule_type: "balance_check",
        description: "Total payment_amount must match source within 0.5%",
        severity: "critical",
        column: "payment_amount",
        threshold: 0.005,
      },
      {
        rule_id: "rule-claims-003",
        rule_type: "null_rate",
        description: "payment_id null rate must be 0",
        severity: "critical",
        column: "payment_id",
        threshold: 0,
      },
      {
        rule_id: "rule-claims-004",
        rule_type: "duplicate_key",
        description: "payment_id must be unique",
        severity: "critical",
        column: "payment_id",
        threshold: 0,
      },
    ],
    downstream_consumers: ["Claims Payment Analysis", "Reserve Adequacy Report", "Finance Ledger"],
  },
  "dp-retail-sales": {
    product_id: "dp-retail-sales",
    product_name: "Retail Sales Performance",
    owner: "Fatima Al-Rashid",
    business_domain: "Retail Sales",
    source_systems: ["POS System", "ERP"],
    primary_key: "order_id",
    freshness_expectation: "Daily load by 06:00 UTC",
    columns: [
      { name: "order_id", data_type: "STRING", nullable: false, description: "Unique order identifier" },
      { name: "order_date", data_type: "DATE", nullable: false, description: "Transaction date" },
      { name: "product_id", data_type: "STRING", nullable: false, description: "Product SKU reference" },
      {
        name: "region",
        data_type: "STRING",
        nullable: false,
        description: "Sales region",
        allowed_categories: ["NORTH", "SOUTH", "EAST", "WEST", "ONLINE"],
      },
      {
        name: "quantity",
        data_type: "INTEGER",
        nullable: false,
        description: "Units sold",
        allowed_range: "1 to 10000",
      },
      {
        name: "unit_price",
        data_type: "DECIMAL(10,2)",
        nullable: false,
        description: "Sale price per unit",
        allowed_range: "0.01 to 100000",
      },
      {
        name: "discount_pct",
        data_type: "DECIMAL(5,4)",
        nullable: true,
        description: "Applied discount percentage",
        allowed_range: "0 to 0.75",
      },
      { name: "total_amount", data_type: "DECIMAL(14,2)", nullable: false, description: "Net order value" },
    ],
    reconciliation_rules: [
      {
        rule_id: "rule-retail-001",
        rule_type: "row_count",
        description: "Order count must match source within 0.5%",
        severity: "medium",
        column: null,
        threshold: 0.005,
      },
      {
        rule_id: "rule-retail-002",
        rule_type: "balance_check",
        description: "Total sales amount must match source within 1%",
        severity: "high",
        column: "total_amount",
        threshold: 0.01,
      },
      {
        rule_id: "rule-retail-003",
        rule_type: "category_distribution",
        description: "Region distribution must not shift >10%",
        severity: "medium",
        column: "region",
        threshold: 0.1,
      },
      {
        rule_id: "rule-retail-004",
        rule_type: "null_rate",
        description: "order_id null rate must be 0",
        severity: "critical",
        column: "order_id",
        threshold: 0,
      },
    ],
    downstream_consumers: ["Retail Sales Performance", "Product Category Dashboard"],
  },
};

export const DATA_PROFILES: Record<string, object> = {
  "dp-reg-positions": {
    product_id: "dp-reg-positions",
    profile_date: "2026-04-30",
    source_row_count: 48200,
    target_row_count: 48187,
    columns: [
      {
        column_name: "position_id",
        data_type: "STRING",
        null_rate: 0.0,
        distinct_count: 48200,
        min_value: "POS-00001",
        max_value: "POS-99999",
        sample_values: ["POS-10234", "POS-20891", "POS-33412"],
      },
      {
        column_name: "reporting_date",
        data_type: "DATE",
        null_rate: 0.0,
        distinct_count: 1,
        min_value: "2026-04-30",
        max_value: "2026-04-30",
        sample_values: ["2026-04-30"],
      },
      {
        column_name: "instrument_type",
        data_type: "STRING",
        null_rate: 0.0,
        distinct_count: 5,
        min_value: null,
        max_value: null,
        sample_values: ["BOND", "EQUITY", "DERIVATIVE", "FX", "REPO"],
      },
      {
        column_name: "notional_amount",
        data_type: "DECIMAL",
        null_rate: 0.002,
        distinct_count: 47108,
        min_value: "1000.00",
        max_value: "985000000.00",
        sample_values: ["250000.00", "1500000.00", "50000000.00"],
      },
      {
        column_name: "risk_weight",
        data_type: "DECIMAL",
        null_rate: 0.0,
        distinct_count: 12,
        min_value: "0.0000",
        max_value: "1.5000",
        sample_values: ["0.0000", "0.2000", "0.5000", "1.0000"],
      },
      {
        column_name: "capital_charge",
        data_type: "DECIMAL",
        null_rate: 0.002,
        distinct_count: 46900,
        min_value: "0.00",
        max_value: "197000000.00",
        sample_values: ["50000.00", "300000.00", "10000000.00"],
      },
    ],
    quality_findings: [
      {
        finding_id: "qf-reg-001",
        severity: "critical",
        category: "row_count_mismatch",
        asset: "fact_positions",
        expected_value: "48200",
        observed_value: "48187",
        evidence:
          "Target row count 13 rows short of source. Missing rows detected in load batch 2026-04-30T05:42:00Z.",
        recommended_action:
          "Investigate pipeline PL_REG_POSITIONS_DAILY batch window. Replay missing records from source.",
      },
      {
        finding_id: "qf-reg-002",
        severity: "medium",
        category: "null_spike",
        asset: "notional_amount",
        expected_value: "null_rate < 0.001",
        observed_value: "null_rate = 0.002",
        evidence: "0.2% null rate on notional_amount vs expected 0.1% threshold. 96 records affected.",
        recommended_action:
          "Inspect source Oracle Financials for recently added instruments with missing notional reference.",
      },
    ],
  },
  "dp-claims-payments": {
    product_id: "dp-claims-payments",
    profile_date: "2026-04-30",
    source_row_count: 12480,
    target_row_count: 12480,
    columns: [
      {
        column_name: "payment_id",
        data_type: "STRING",
        null_rate: 0.0,
        distinct_count: 12480,
        min_value: "PAY-00001",
        max_value: "PAY-99999",
        sample_values: ["PAY-11204", "PAY-22908", "PAY-33601"],
      },
      {
        column_name: "payment_amount",
        data_type: "DECIMAL",
        null_rate: 0.0,
        distinct_count: 9840,
        min_value: "50.00",
        max_value: "1850000.00",
        sample_values: ["1200.00", "45000.00", "250000.00"],
      },
      {
        column_name: "payment_type",
        data_type: "STRING",
        null_rate: 0.0,
        distinct_count: 4,
        min_value: null,
        max_value: null,
        sample_values: ["CLAIM_SETTLEMENT", "PARTIAL_PAYMENT", "RESERVE_RELEASE"],
      },
      {
        column_name: "fraud_score",
        data_type: "DECIMAL",
        null_rate: 0.042,
        distinct_count: 876,
        min_value: "0.001",
        max_value: "0.997",
        sample_values: ["0.023", "0.145", "0.876"],
      },
      {
        column_name: "status",
        data_type: "STRING",
        null_rate: 0.0,
        distinct_count: 4,
        min_value: null,
        max_value: null,
        sample_values: ["PENDING", "PROCESSED", "REJECTED"],
      },
    ],
    quality_findings: [
      {
        finding_id: "qf-claims-001",
        severity: "high",
        category: "null_rate_elevated",
        asset: "fraud_score",
        expected_value: "null_rate < 0.01",
        observed_value: "null_rate = 0.042",
        evidence: "4.2% of payments have no fraud score. ML model likely not scoring new policy types.",
        recommended_action:
          "Verify ML Platform model coverage for new policy lines. Add fallback default score for unscored records.",
      },
      {
        finding_id: "qf-claims-002",
        severity: "high",
        category: "stale_source",
        asset: "dim_policy",
        expected_value: "last_updated within 30 days",
        observed_value: "last_updated = 2026-03-28 (33 days ago)",
        evidence: "Policy dimension table has not been refreshed in 33 days. New policies may be missing.",
        recommended_action:
          "Confirm PL_CLAIMS_PAYMENTS_INGEST failure is resolved and trigger full refresh of dim_policy.",
      },
    ],
  },
  "dp-retail-sales": {
    product_id: "dp-retail-sales",
    profile_date: "2026-04-30",
    source_row_count: 92000,
    target_row_count: 92000,
    columns: [
      {
        column_name: "order_id",
        data_type: "STRING",
        null_rate: 0.0,
        distinct_count: 92000,
        min_value: "ORD-000001",
        max_value: "ORD-999999",
        sample_values: ["ORD-102345", "ORD-234891", "ORD-381204"],
      },
      {
        column_name: "order_date",
        data_type: "DATE",
        null_rate: 0.0,
        distinct_count: 90,
        min_value: "2026-02-01",
        max_value: "2026-04-30",
        sample_values: ["2026-03-15", "2026-04-01", "2026-04-28"],
      },
      {
        column_name: "region",
        data_type: "STRING",
        null_rate: 0.0,
        distinct_count: 5,
        min_value: null,
        max_value: null,
        sample_values: ["NORTH", "SOUTH", "EAST", "WEST", "ONLINE"],
      },
      {
        column_name: "quantity",
        data_type: "INTEGER",
        null_rate: 0.0,
        distinct_count: 184,
        min_value: "1",
        max_value: "500",
        sample_values: ["1", "5", "12", "50"],
      },
      {
        column_name: "total_amount",
        data_type: "DECIMAL",
        null_rate: 0.0,
        distinct_count: 89200,
        min_value: "0.99",
        max_value: "450000.00",
        sample_values: ["24.99", "199.00", "1850.00"],
      },
    ],
    quality_findings: [],
  },
};

export function getProductById(productId: string) {
  return DATA_PRODUCTS.find((p) => p.product_id === productId);
}

export function getContractById(productId: string) {
  return DATA_CONTRACTS[productId];
}

export function getProfileById(productId: string) {
  return DATA_PROFILES[productId];
}
