export const DOMAINS = [
  {
    domain_id: "dom-regulatory",
    domain_name: "Regulatory Reporting",
    description: "Compliance positions, capital requirements, and regulatory submissions — reference domain.",
    owner: "Priya Sharma",
    criticality: "critical",
    asset_count: 18,
    pipeline_count: 7,
    readiness_band: "needs_review",
  },
  {
    domain_id: "dom-claims",
    domain_name: "Claims Finance",
    description: "Insurance claims payment analytics and reserve calculations — reference domain.",
    owner: "Marcus Chen",
    criticality: "high",
    asset_count: 14,
    pipeline_count: 5,
    readiness_band: "blocked",
  },
  {
    domain_id: "dom-retail",
    domain_name: "Retail Sales",
    description: "Point-of-sale transactions, product performance, and regional sales analysis — reference domain.",
    owner: "Fatima Al-Rashid",
    criticality: "medium",
    asset_count: 11,
    pipeline_count: 4,
    readiness_band: "ready",
  },
  {
    domain_id: "dom-customer",
    domain_name: "Customer Analytics",
    description: "Customer segmentation, lifetime value, and behavioural cohorts — reference domain.",
    owner: "James Okonkwo",
    criticality: "medium",
    asset_count: 9,
    pipeline_count: 3,
    readiness_band: "needs_review",
  },
  {
    domain_id: "dom-ops",
    domain_name: "Operations Monitoring",
    description: "Infrastructure health, pipeline SLA tracking, and cost attribution — reference domain.",
    owner: "Lin Wei",
    criticality: "low",
    asset_count: 6,
    pipeline_count: 2,
    readiness_band: "ready",
  },
] as const;

export const WORKSPACES = [
  {
    workspace_id: "ws-001",
    workspace_name: "SYNAPSE-REG-PROD",
    business_domain: "Regulatory Reporting",
    environment: "production",
    sql_pool_count: 3,
    spark_pool_count: 1,
    linked_storage: "adls://datalake-reg-prod/",
    owner: "Priya Sharma",
    criticality: "critical",
    estimated_monthly_cost: 4800.0,
    migration_candidate: true,
  },
  {
    workspace_id: "ws-002",
    workspace_name: "SYNAPSE-CLAIMS-PROD",
    business_domain: "Claims Finance",
    environment: "production",
    sql_pool_count: 2,
    spark_pool_count: 2,
    linked_storage: "adls://datalake-claims-prod/",
    owner: "Marcus Chen",
    criticality: "high",
    estimated_monthly_cost: 3600.0,
    migration_candidate: true,
  },
  {
    workspace_id: "ws-003",
    workspace_name: "SYNAPSE-RETAIL-UAT",
    business_domain: "Retail Sales",
    environment: "uat",
    sql_pool_count: 1,
    spark_pool_count: 1,
    linked_storage: "adls://datalake-retail-uat/",
    owner: "Fatima Al-Rashid",
    criticality: "medium",
    estimated_monthly_cost: 1200.0,
    migration_candidate: true,
  },
  {
    workspace_id: "ws-004",
    workspace_name: "SYNAPSE-CUSTOMER-DEV",
    business_domain: "Customer Analytics",
    environment: "development",
    sql_pool_count: 1,
    spark_pool_count: 0,
    linked_storage: "adls://datalake-customer-dev/",
    owner: "James Okonkwo",
    criticality: "medium",
    estimated_monthly_cost: 650.0,
    migration_candidate: false,
  },
  {
    workspace_id: "ws-005",
    workspace_name: "SYNAPSE-OPS-SHARED",
    business_domain: "Operations Monitoring",
    environment: "production",
    sql_pool_count: 1,
    spark_pool_count: 0,
    linked_storage: "adls://datalake-ops-shared/",
    owner: "Lin Wei",
    criticality: "low",
    estimated_monthly_cost: 480.0,
    migration_candidate: true,
  },
  {
    workspace_id: "ws-006",
    workspace_name: "SYNAPSE-REG-DEV",
    business_domain: "Regulatory Reporting",
    environment: "development",
    sql_pool_count: 1,
    spark_pool_count: 0,
    linked_storage: "adls://datalake-reg-dev/",
    owner: "Priya Sharma",
    criticality: "low",
    estimated_monthly_cost: 320.0,
    migration_candidate: false,
  },
];

export const PIPELINES = [
  {
    pipeline_id: "adf-001",
    pipeline_name: "PL_REG_POSITIONS_DAILY",
    source_system: "Oracle Financials",
    target_system: "SYNAPSE-REG-PROD",
    schedule: "0 6 * * 1-5",
    trigger_type: "scheduled",
    activity_count: 14,
    dependency_count: 3,
    last_run_status: "succeeded",
    average_runtime_minutes: 42.5,
    owner: "Priya Sharma",
    business_domain: "Regulatory Reporting",
    complexity: "high",
  },
  {
    pipeline_id: "adf-002",
    pipeline_name: "PL_REG_CAPITAL_CALC",
    source_system: "SYNAPSE-REG-PROD",
    target_system: "SYNAPSE-REG-PROD",
    schedule: "0 8 * * 1-5",
    trigger_type: "scheduled",
    activity_count: 22,
    dependency_count: 5,
    last_run_status: "succeeded",
    average_runtime_minutes: 78.0,
    owner: "Priya Sharma",
    business_domain: "Regulatory Reporting",
    complexity: "high",
  },
  {
    pipeline_id: "adf-003",
    pipeline_name: "PL_CLAIMS_PAYMENTS_INGEST",
    source_system: "Policy Management System",
    target_system: "SYNAPSE-CLAIMS-PROD",
    schedule: "0 */4 * * *",
    trigger_type: "scheduled",
    activity_count: 9,
    dependency_count: 2,
    last_run_status: "failed",
    average_runtime_minutes: 18.0,
    owner: "Marcus Chen",
    business_domain: "Claims Finance",
    complexity: "medium",
  },
  {
    pipeline_id: "adf-004",
    pipeline_name: "PL_CLAIMS_RESERVE_CALC",
    source_system: "SYNAPSE-CLAIMS-PROD",
    target_system: "SYNAPSE-CLAIMS-PROD",
    schedule: "0 9 * * 1",
    trigger_type: "scheduled",
    activity_count: 18,
    dependency_count: 4,
    last_run_status: "succeeded",
    average_runtime_minutes: 95.0,
    owner: "Marcus Chen",
    business_domain: "Claims Finance",
    complexity: "high",
  },
  {
    pipeline_id: "adf-005",
    pipeline_name: "PL_RETAIL_SALES_DAILY",
    source_system: "POS System",
    target_system: "SYNAPSE-RETAIL-UAT",
    schedule: "0 2 * * *",
    trigger_type: "scheduled",
    activity_count: 7,
    dependency_count: 1,
    last_run_status: "succeeded",
    average_runtime_minutes: 12.5,
    owner: "Fatima Al-Rashid",
    business_domain: "Retail Sales",
    complexity: "low",
  },
  {
    pipeline_id: "adf-006",
    pipeline_name: "PL_RETAIL_PRODUCT_MASTER",
    source_system: "ERP",
    target_system: "SYNAPSE-RETAIL-UAT",
    schedule: "0 1 * * 0",
    trigger_type: "scheduled",
    activity_count: 5,
    dependency_count: 1,
    last_run_status: "succeeded",
    average_runtime_minutes: 8.0,
    owner: "Fatima Al-Rashid",
    business_domain: "Retail Sales",
    complexity: "low",
  },
  {
    pipeline_id: "adf-007",
    pipeline_name: "PL_CUSTOMER_SEGMENTATION",
    source_system: "CRM",
    target_system: "SYNAPSE-CUSTOMER-DEV",
    schedule: "0 3 * * 0",
    trigger_type: "scheduled",
    activity_count: 11,
    dependency_count: 2,
    last_run_status: "succeeded",
    average_runtime_minutes: 35.0,
    owner: "James Okonkwo",
    business_domain: "Customer Analytics",
    complexity: "medium",
  },
  {
    pipeline_id: "adf-008",
    pipeline_name: "PL_OPS_COST_ATTRIBUTION",
    source_system: "Azure Cost Management",
    target_system: "SYNAPSE-OPS-SHARED",
    schedule: "0 0 1 * *",
    trigger_type: "scheduled",
    activity_count: 6,
    dependency_count: 1,
    last_run_status: "succeeded",
    average_runtime_minutes: 5.5,
    owner: "Lin Wei",
    business_domain: "Operations Monitoring",
    complexity: "low",
  },
  {
    pipeline_id: "adf-009",
    pipeline_name: "PL_REG_COUNTERPARTY_EXPOSURE",
    source_system: "Risk Platform",
    target_system: "SYNAPSE-REG-PROD",
    schedule: "0 7 * * 1-5",
    trigger_type: "event",
    activity_count: 16,
    dependency_count: 4,
    last_run_status: "succeeded",
    average_runtime_minutes: 55.0,
    owner: "Priya Sharma",
    business_domain: "Regulatory Reporting",
    complexity: "high",
  },
  {
    pipeline_id: "adf-010",
    pipeline_name: "PL_CLAIMS_FRAUD_SCORE",
    source_system: "ML Platform",
    target_system: "SYNAPSE-CLAIMS-PROD",
    schedule: "0 10 * * 1-5",
    trigger_type: "event",
    activity_count: 13,
    dependency_count: 3,
    last_run_status: "failed",
    average_runtime_minutes: 48.0,
    owner: "Marcus Chen",
    business_domain: "Claims Finance",
    complexity: "high",
  },
  {
    pipeline_id: "adf-011",
    pipeline_name: "PL_CUSTOMER_LTV_CALC",
    source_system: "SYNAPSE-CUSTOMER-DEV",
    target_system: "SYNAPSE-CUSTOMER-DEV",
    schedule: "0 4 * * 0",
    trigger_type: "scheduled",
    activity_count: 9,
    dependency_count: 2,
    last_run_status: "succeeded",
    average_runtime_minutes: 28.0,
    owner: "James Okonkwo",
    business_domain: "Customer Analytics",
    complexity: "medium",
  },
  {
    pipeline_id: "adf-012",
    pipeline_name: "PL_OPS_PIPELINE_SLA",
    source_system: "Azure Monitor",
    target_system: "SYNAPSE-OPS-SHARED",
    schedule: "0 */6 * * *",
    trigger_type: "scheduled",
    activity_count: 4,
    dependency_count: 0,
    last_run_status: "succeeded",
    average_runtime_minutes: 3.0,
    owner: "Lin Wei",
    business_domain: "Operations Monitoring",
    complexity: "low",
  },
];

export const SQL_OBJECTS = [
  {
    object_id: "sql-001",
    schema_name: "reg",
    object_name: "fact_positions",
    object_type: "table",
    row_count: 4820000,
    size_mb: 1840.0,
    primary_key: "position_id",
    partition_column: "reporting_date",
    last_updated: "2026-04-30",
    downstream_reports: 6,
    sensitive_data_flag: true,
    owner: "Priya Sharma",
  },
  {
    object_id: "sql-002",
    schema_name: "reg",
    object_name: "dim_counterparty",
    object_type: "table",
    row_count: 12500,
    size_mb: 24.5,
    primary_key: "counterparty_id",
    partition_column: null,
    last_updated: "2026-04-15",
    downstream_reports: 4,
    sensitive_data_flag: true,
    owner: "Priya Sharma",
  },
  {
    object_id: "sql-003",
    schema_name: "reg",
    object_name: "agg_capital_requirements",
    object_type: "view",
    row_count: 3200,
    size_mb: 2.1,
    primary_key: null,
    partition_column: null,
    last_updated: "2026-04-30",
    downstream_reports: 3,
    sensitive_data_flag: false,
    owner: "Priya Sharma",
  },
  {
    object_id: "sql-004",
    schema_name: "claims",
    object_name: "fact_payments",
    object_type: "table",
    row_count: 2180000,
    size_mb: 890.0,
    primary_key: "payment_id",
    partition_column: "payment_date",
    last_updated: "2026-04-29",
    downstream_reports: 4,
    sensitive_data_flag: true,
    owner: "Marcus Chen",
  },
  {
    object_id: "sql-005",
    schema_name: "claims",
    object_name: "dim_policy",
    object_type: "table",
    row_count: 345000,
    size_mb: 142.0,
    primary_key: "policy_id",
    partition_column: null,
    last_updated: "2026-03-28",
    downstream_reports: 5,
    sensitive_data_flag: true,
    owner: "Marcus Chen",
  },
  {
    object_id: "sql-006",
    schema_name: "claims",
    object_name: "agg_reserve_summary",
    object_type: "view",
    row_count: 1800,
    size_mb: 0.8,
    primary_key: null,
    partition_column: null,
    last_updated: "2026-04-29",
    downstream_reports: 2,
    sensitive_data_flag: false,
    owner: "Marcus Chen",
  },
  {
    object_id: "sql-007",
    schema_name: "retail",
    object_name: "fact_sales_orders",
    object_type: "table",
    row_count: 9200000,
    size_mb: 3100.0,
    primary_key: "order_id",
    partition_column: "order_date",
    last_updated: "2026-04-30",
    downstream_reports: 5,
    sensitive_data_flag: false,
    owner: "Fatima Al-Rashid",
  },
  {
    object_id: "sql-008",
    schema_name: "retail",
    object_name: "dim_product",
    object_type: "table",
    row_count: 52000,
    size_mb: 18.5,
    primary_key: "product_id",
    partition_column: null,
    last_updated: "2026-04-21",
    downstream_reports: 3,
    sensitive_data_flag: false,
    owner: "Fatima Al-Rashid",
  },
  {
    object_id: "sql-009",
    schema_name: "retail",
    object_name: "agg_sales_by_region",
    object_type: "view",
    row_count: 2400,
    size_mb: 0.5,
    primary_key: null,
    partition_column: null,
    last_updated: "2026-04-30",
    downstream_reports: 3,
    sensitive_data_flag: false,
    owner: "Fatima Al-Rashid",
  },
  {
    object_id: "sql-010",
    schema_name: "customer",
    object_name: "fact_customer_events",
    object_type: "table",
    row_count: 6700000,
    size_mb: 2240.0,
    primary_key: "event_id",
    partition_column: "event_date",
    last_updated: "2026-04-28",
    downstream_reports: 2,
    sensitive_data_flag: true,
    owner: "James Okonkwo",
  },
  {
    object_id: "sql-011",
    schema_name: "customer",
    object_name: "dim_customer",
    object_type: "table",
    row_count: 890000,
    size_mb: 320.0,
    primary_key: "customer_id",
    partition_column: null,
    last_updated: "2026-04-25",
    downstream_reports: 3,
    sensitive_data_flag: true,
    owner: "James Okonkwo",
  },
  {
    object_id: "sql-012",
    schema_name: "ops",
    object_name: "fact_pipeline_runs",
    object_type: "table",
    row_count: 142000,
    size_mb: 28.0,
    primary_key: "run_id",
    partition_column: "run_date",
    last_updated: "2026-04-30",
    downstream_reports: 1,
    sensitive_data_flag: false,
    owner: "Lin Wei",
  },
  {
    object_id: "sql-013",
    schema_name: "ops",
    object_name: "agg_cost_by_domain",
    object_type: "view",
    row_count: 120,
    size_mb: 0.1,
    primary_key: null,
    partition_column: null,
    last_updated: "2026-04-30",
    downstream_reports: 1,
    sensitive_data_flag: false,
    owner: "Lin Wei",
  },
  {
    object_id: "sql-014",
    schema_name: "reg",
    object_name: "stg_raw_positions",
    object_type: "table",
    row_count: 5100000,
    size_mb: 1920.0,
    primary_key: null,
    partition_column: "load_date",
    last_updated: "2026-04-30",
    downstream_reports: 0,
    sensitive_data_flag: true,
    owner: "Priya Sharma",
  },
];

export const REPORTS = [
  {
    report_id: "pbi-001",
    report_name: "Regulatory Capital Dashboard",
    workspace_name: "RegCompliance-Reports",
    dataset_name: "DS_Capital_Requirements",
    refresh_frequency: "daily",
    dependent_tables: ["reg.fact_positions", "reg.agg_capital_requirements"],
    row_level_security: true,
    direct_query_flag: false,
    business_owner: "Priya Sharma",
    criticality: "critical",
  },
  {
    report_id: "pbi-002",
    report_name: "Counterparty Exposure Monitor",
    workspace_name: "RegCompliance-Reports",
    dataset_name: "DS_Counterparty_Risk",
    refresh_frequency: "daily",
    dependent_tables: ["reg.fact_positions", "reg.dim_counterparty"],
    row_level_security: true,
    direct_query_flag: true,
    business_owner: "Priya Sharma",
    criticality: "critical",
  },
  {
    report_id: "pbi-003",
    report_name: "Claims Payment Analysis",
    workspace_name: "Claims-Insights",
    dataset_name: "DS_Claims_Payments",
    refresh_frequency: "daily",
    dependent_tables: ["claims.fact_payments", "claims.dim_policy"],
    row_level_security: false,
    direct_query_flag: false,
    business_owner: "Marcus Chen",
    criticality: "high",
  },
  {
    report_id: "pbi-004",
    report_name: "Reserve Adequacy Report",
    workspace_name: "Claims-Insights",
    dataset_name: "DS_Reserve_Summary",
    refresh_frequency: "weekly",
    dependent_tables: ["claims.agg_reserve_summary", "claims.dim_policy"],
    row_level_security: true,
    direct_query_flag: false,
    business_owner: "Marcus Chen",
    criticality: "high",
  },
  {
    report_id: "pbi-005",
    report_name: "Retail Sales Performance",
    workspace_name: "Retail-Analytics",
    dataset_name: "DS_Sales_Performance",
    refresh_frequency: "daily",
    dependent_tables: ["retail.fact_sales_orders", "retail.dim_product", "retail.agg_sales_by_region"],
    row_level_security: false,
    direct_query_flag: false,
    business_owner: "Fatima Al-Rashid",
    criticality: "medium",
  },
  {
    report_id: "pbi-006",
    report_name: "Product Category Dashboard",
    workspace_name: "Retail-Analytics",
    dataset_name: "DS_Product_Category",
    refresh_frequency: "weekly",
    dependent_tables: ["retail.fact_sales_orders", "retail.dim_product"],
    row_level_security: false,
    direct_query_flag: false,
    business_owner: "Fatima Al-Rashid",
    criticality: "medium",
  },
  {
    report_id: "pbi-007",
    report_name: "Customer Segmentation View",
    workspace_name: "Customer-Insights",
    dataset_name: "DS_Customer_Segments",
    refresh_frequency: "weekly",
    dependent_tables: ["customer.fact_customer_events", "customer.dim_customer"],
    row_level_security: true,
    direct_query_flag: false,
    business_owner: "James Okonkwo",
    criticality: "medium",
  },
  {
    report_id: "pbi-008",
    report_name: "Operations Health Monitor",
    workspace_name: "Ops-Platform",
    dataset_name: "DS_Ops_Health",
    refresh_frequency: "hourly",
    dependent_tables: ["ops.fact_pipeline_runs", "ops.agg_cost_by_domain"],
    row_level_security: false,
    direct_query_flag: true,
    business_owner: "Lin Wei",
    criticality: "low",
  },
];
